# SPDX-License-Identifier: Apache-2.0
# Docker configuration for Fabric Peer containers

version: "3"

networks:
  ecko:
    external:
      name: ecko-network

services:
  peer0.eckochain.example.com:
    container_name: peer0.eckochain.example.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer0.eckochain.example.com
      - CORE_PEER_NETWORKID=dev
      - CORE_PEER_ADDRESS=peer0.eckochain.example.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.eckochain.example.com:7052
      - CORE_PEER_CHAINCODEADDRESS=peer0.eckochain.example.com:7052
      - CORE_PEER_LOCALMSPID=eckochain.example.com-MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_FILESYSTEMPATH=/var/hyperledger/production
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.eckochain.example.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.eckochain.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.eckochain.example.com:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_GOSSIP_STATE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/peer0.eckochain.example.com-tlscert.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/peer0.eckochain.example.com-priv.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/msp/tlscacerts/tlsca.eckochain.example.com-cert.crt
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=true
      - CORE_PEER_TLS_CLIENTCERT_FILE=/etc/hyperledger/fabric/tls/peer0.eckochain.example.com-tlscert.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=/etc/hyperledger/fabric/tls/peer0.eckochain.example.com-priv.key
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/fabric/msp/tlscacerts/tlsca.eckochain.example.com-cert.crt
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_CHAINCODE_EXECUTETIMEOUT=60s
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.eckochain.example.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=secret
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ecko-network
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    restart: unless-stopped
    volumes:
      - /var/run/:/host/var/run/
      - /eckostorage/fabric_data/crypto-config/peer0.eckochain.example.com/enca/msp:/etc/hyperledger/fabric/msp
      - /eckostorage/fabric_data/crypto-config/peer0.eckochain.example.com/enca/tls:/etc/hyperledger/fabric/tls
      - /eckostorage/fabric_data/production/peer0.eckochain.example.com:/var/hyperledger/production
    ports:
      - 7051:7051
    networks:
      - ecko
    command: peer node start
    depends_on:
      - couchdb0.eckochain.example.com
    logging:
        driver: local

  couchdb0.eckochain.example.com:
    container_name: couchdb0.eckochain.example.com
    image: couchdb:3.2.2
    environment:
      - COUCHDB_USER=peer
      - COUCHDB_PASSWORD=secret
    networks:
      - ecko
    logging:
        driver: local
